# Generated by Django 5.0.4 on 2024-04-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20210522_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Property', 'Property'), ('Mobiles', 'Mobiles'), ('Bikes', 'Bikes'), ('Jobs', 'Jobs'), ('Cars', 'Cars'), ('Fashion', 'Fashion'), ('Books&Sports', 'Books&Sports'), ('Furniture', 'Furniture'), ('Electronics', 'Electronics')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('KA', 'Karnataka'), ('AP', 'Andhra Pradesh'), ('PB', 'Punjab'), ('GA', 'Goa'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('RJ', 'Rajasthan'), ('MP', 'Madhya Pradesh'), ('OD', 'Odisha'), ('MZ', 'Mizoram'), ('TS', 'Telegana'), ('BR', 'Bihar'), ('WB', 'West Bengal'), ('TN', 'Tamil Nadu'), ('UP', 'Uttar Pradesh'), ('JH', 'Jharkhand'), ('AS', 'Assam'), ('CG', 'Chhattisgarh'), ('TR', 'Tripura'), ('UK', 'Uttarakhand'), ('NL', 'Nagaland'), ('KL', 'Kerala'), ('GJ', 'Gujarat'), ('MH', 'Maharashtra'), ('HP', 'Haryana'), ('MI', 'Sikkim'), ('AR', 'Arunachal Pradesh')], max_length=100),
        ),
    ]
